# Generated by Django 5.2.7 on 2025-10-24 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsPatient',
            fields=[
                ('patient', models.OneToOneField(help_text='Lien unique vers le compte utilisateur (patient).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details_dossier', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('antecedents_medicaux', models.TextField(blank=True, default='', help_text='Historique des maladies chroniques, chirurgies majeures, hospitalisations.')),
                ('allergies', models.TextField(blank=True, default='', help_text='Allergies médicamenteuses ou alimentaires (CRITIQUE).')),
                ('tension_reference_systolique', models.IntegerField(blank=True, help_text='Tension Systolique de référence (mmHg).', null=True)),
                ('tension_reference_diastolique', models.IntegerField(blank=True, help_text='Tension Diastolique de référence (mmHg).', null=True)),
                ('poids_initial', models.DecimalField(blank=True, decimal_places=2, help_text='Poids enregistré au début du suivi (kg).', max_digits=5, null=True)),
                ('taille_cm', models.IntegerField(blank=True, help_text='Taille du patient (cm).', null=True)),
                ('contact_urgence_nom', models.CharField(blank=True, help_text="Nom de la personne à contacter en cas d'urgence.", max_length=100)),
                ('contact_urgence_telephone', models.CharField(blank=True, help_text="Téléphone du contact d'urgence.", max_length=20)),
            ],
            options={
                'verbose_name': 'Détail Patient',
                'verbose_name_plural': 'Détails Patients',
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
