# Generated by Django 5.2.7 on 2025-10-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_detailspatient_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailspatient',
            name='contact_urgence_lien',
            field=models.CharField(choices=[('PR', 'Proche Parent'), ('CO', 'Conjoint(e)'), ('AM', 'Ami(e)'), ('AU', 'Autre')], default='AU', help_text='Spécifiez le lien entre vous et cette personne.', max_length=2, verbose_name='Lien de parenté ou relation'),
        ),
        migrations.AlterField(
            model_name='detailspatient',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom complet de la personne à contacter en cas d'urgence"),
        ),
        migrations.AlterField(
            model_name='detailspatient',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone de la personne à contacter en cas d'urgence"),
        ),
    ]
