# Generated by Django 5.2.7 on 2025-11-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_detailspatient_contact_urgence_lien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailspatient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Allergies médicamenteuses ou alimentaires (CRITIQUE).'),
        ),
        migrations.AlterField(
            model_name='detailspatient',
            name='antecedents_medicaux',
            field=models.TextField(blank=True, help_text='Historique des maladies chroniques, chirurgies majeures, hospitalisations.'),
        ),
    ]
