# Generated by Django 5.2.7 on 2025-11-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_detailspatient_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailspatient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Allergies médicamenteuses ou alimentaires (CRITIQUE).', null=True),
        ),
        migrations.AlterField(
            model_name='detailspatient',
            name='antecedents_medicaux',
            field=models.TextField(blank=True, help_text='Historique des maladies chroniques, chirurgies majeures, hospitalisations.', null=True),
        ),
    ]
