# Generated by Django 5.2.7 on 2025-11-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_detailspatient_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailspatient',
            name='glycemie_reference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Niveau de glycémie de référence (mg/dL ou mmol/L).', max_digits=5, null=True),
        ),
    ]
