# Generated by Django 5.2.7 on 2025-11-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_detailspatient_glycemie_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailspatient',
            name='glycemie_reference',
        ),
        migrations.RemoveField(
            model_name='detailspatient',
            name='poids_initial',
        ),
        migrations.RemoveField(
            model_name='detailspatient',
            name='tension_reference_diastolique',
        ),
        migrations.RemoveField(
            model_name='detailspatient',
            name='tension_reference_systolique',
        ),
    ]
