# Generated by Django 5.2.7 on 2025-11-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_detailspatient_glycemie_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='numero_urgence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
