# Generated by Django 5.2.7 on 2025-11-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_patient_numero_urgence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailspatient',
            name='contact_urgence_lien',
            field=models.CharField(choices=[('PR', 'Parent'), ('CO', 'Conjoint(e)'), ('EN', 'Enfant'), ('FR', 'Frère/Soeur'), ('AM', 'Ami(e)'), ('AU', 'Autre')], default='AU', help_text='Spécifiez le lien entre vous et cette personne.', max_length=2, verbose_name='Lien de parenté ou relation'),
        ),
    ]
