# Generated by Django 5.2.7 on 2025-10-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(help_text='Date et heure prévues du rendez-vous.')),
                ('motif', models.CharField(help_text='Motif du rendez-vous (ex: consultation de routine, contrôle, etc.).', max_length=150)),
                ('statut', models.CharField(choices=[('P', 'Planifié'), ('C', 'Confirmé'), ('A', 'Annulé'), ('T', 'Terminé')], default='P', help_text='Statut actuel du rendez-vous.', max_length=1)),
                ('notes_internes', models.TextField(blank=True, help_text='Notes pour le personnel du centre (ex: préparation spéciale).', null=True)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suivi', models.DateTimeField(auto_now_add=True, help_text="Date et heure de l'enregistrement.")),
                ('motif', models.CharField(help_text='Motif principal de la visite.', max_length=255)),
                ('notes_medecin', models.TextField(help_text='Observations, diagnostic, et plan de soins.')),
                ('prescriptions', models.TextField(blank=True, help_text='Détails des médicaments ou traitements prescrits (facultatif).', null=True)),
            ],
            options={
                'verbose_name': 'Suivi/Observation',
                'verbose_name_plural': 'Suivis et Observations',
                'ordering': ['-date_suivi'],
            },
        ),
    ]
