# Generated by Django 5.2.7 on 2025-10-17 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(help_text='Le patient qui a pris le rendez-vous.', on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suivi',
            name='patient',
            field=models.ForeignKey(help_text='Le patient concerné par ce suivi.', on_delete=django.db.models.deletion.CASCADE, related_name='suivis_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
