# Generated by Django 5.2.7 on 2025-10-24 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la saisie.')),
                ('tension_systolique', models.IntegerField(blank=True, help_text='Tension Systolique (mmHg).', null=True)),
                ('tension_diastolique', models.IntegerField(blank=True, help_text='Tension Diastolique (mmHg).', null=True)),
                ('glycemie', models.DecimalField(blank=True, decimal_places=2, help_text='Niveau de glycémie (g/L ou mmol/L).', max_digits=5, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, help_text='Poids actuel (kg).', max_digits=5, null=True)),
                ('notes_patient', models.TextField(blank=True, help_text='Commentaires ou symptômes ressentis par le patient.')),
                ('patient', models.ForeignKey(help_text='Le patient ayant effectué le relevé.', on_delete=django.db.models.deletion.CASCADE, related_name='releves_vitaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relevé Vital',
                'verbose_name_plural': 'Relevés Vitaux',
                'ordering': ['-date_releve'],
            },
        ),
    ]
